#24 Add user card
apastuhov/sigma-js-internship-2020 pull request #39
Opened 2020-10-16 09:52 UTC by OrestHaponov

2020-10-16 10:59 UTC, apastuhov requested changes
LGTM

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/pages/profile/profile.scss
> +  width: 944px;
remove after integration with Layout

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +import User from '../../util/user.json';
user-mock.json

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +        <img src={UserPhoto} alt="" />
fullfill alt like "photo of {username}"

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +    event.preventDefault();
console.log("Add XYZ to friend");

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +        <img src={UserPhoto} alt="" />
move image to separate component

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +      top: 95px;
use bottom

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +      border-radius: 15px;
50%

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +      span {
.flag

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +        padding-left: 13px;
variable 14

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +        display: flex;
review css-grid usage

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +      position: absolute;
use flex

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +          padding-left: $small-retreat;
gap-4
gap-8
gap-12
gap-16
gap-24
gap-36

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +@media screen and (max-width: 540px) {
to variable

2020-10-16 10:59 UTC, apastuhov commented on frontend/src/components/shared/userCard/userCard.scss
> +    flex-direction: column;
to selector as \@ media mobile

2020-10-17 19:34 UTC, dromix approved these changes
LGTM

2020-10-17 20:29 UTC, merged