Added user service/model for registration
apastuhov/sigma-js-internship-2020 pull request #67
Opened 2020-10-27 15:14 UTC by dromix

2020-10-28 08:27 UTC, Pr1sm0 approved these changes
LGTM

2020-10-28 21:24 UTC, oleksandrstarov requested changes

2020-10-28 21:24 UTC, oleksandrstarov commented on backend/src/controller/index.ts
> +import postRoute from './post';
please align namings usersRoute but postRoute seems inconsistent and then routes are user and posts

2020-10-28 21:24 UTC, oleksandrstarov commented on backend/src/data/models/user.ts
> +  sex: Number,
really?

2020-10-28 21:24 UTC, oleksandrstarov commented on backend/src/data/repository/post.ts
> +  }
potential issue here - we creating post and return this directly. Not the saved copy which comes as second param from callback function

2020-10-29 09:50 UTC, oleksandrstarov approved these changes

2020-10-29 10:38 UTC, merged