#63 Add search improvments
apastuhov/sigma-js-internship-2020 pull request #69
Opened 2020-10-27 18:27 UTC by Pr1sm0

2020-10-28 21:46 UTC, oleksandrstarov requested changes

2020-10-28 21:46 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
>      return Boolean(checkboxFilters.male) ? 0 : 1;
other is not considered here

2020-10-28 21:46 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
> +    apiService(dataType.users).then(users => setUsers(users));
please use await

2020-10-28 21:46 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
> +    ) {
const genderFilters = Object.values(checkboxFilters);

if (genderFilters.every(e=>e) || genderFilters.every(e=>!e)) { return; }

2020-10-28 21:46 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
> +  const hightYears = [...Array(hightLimit - lowLimit)].map((_, index) => hightLimit - index);
no need to do the same, maybe we can const hightYears = [... lowYears].reverse()?

2020-10-29 09:48 UTC, Pr1sm0 commented
Could you have a look now, please?

2020-10-29 09:58 UTC, oleksandrstarov approved these changes
Please check the comments

2020-10-29 09:58 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
> +      await apiService(dataType.users).then(users => setUsers(users));
the point was to 

const user = await apiService(dataType.users);

setUsers(users)

2020-10-29 09:58 UTC, oleksandrstarov commented on frontend/src/components/pages/search/Search.tsx
> +    }
I think we need to use Enum here instead of plain numbers

2020-10-29 10:13 UTC, merged