Feature/adding functional to pages
apastuhov/sigma-js-internship-2020 pull request #70
Opened 2020-10-28 09:22 UTC by romanazaruk

2020-10-28 22:12 UTC, oleksandrstarov requested changes

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/constants/constants.ts
> +export const sex = ['Male', 'Female', 'Other'];
not sure I get this...

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/InputWithFormik/InputWithFormik.tsx
> +  max?: string;
what Max stands for? Maybe should be number?

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/previewInfo/PreviewInfo.tsx
> +  const old = getOld(values.birthday);
Rename to calculateAge
Use moment for this (I believe this is already in the application)

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/previewInfo/PreviewInfo.tsx
> +  };
what the purpose for this? Do we ever use this method?

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/select/Select.tsx
> +};
why do we need separate function? It is used only in one place
<select className="select" onChange={props.onChange} name={props.name} value={props.value}>
        {props.options.map((item, i) => (
    <option key={`${item}${i}`} value={item}>
      {item}
    </option>}
      </select>

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +        {mainInfo.age ? <p>{mainInfo.age} y.o.</p> : null}
can be 

{mainInfo.age && <p>{mainInfo.age} y.o.</p>}

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/userCard/UserCard.tsx
> +            {mainInfo.isFriend ? null : (
same as above

2020-10-28 22:12 UTC, oleksandrstarov commented on frontend/src/components/shared/userPhoto/UserPhoto.tsx
> +    return url.match(/\.(jpeg|jpg|gif|png)$/) != null || url.startsWith('blob:');
maybe 
/blob:|\.(jpeg|jpg|gif|png)/.test(url) ?

2020-10-30 17:03 UTC, OrestHaponov approved these changes
Lgtm

2020-10-30 17:15 UTC, romanazaruk commented on frontend/src/components/shared/previewInfo/PreviewInfo.tsx
> +  };
Thats send the country code

2020-10-30 17:15 UTC, romanazaruk commented on frontend/src/components/shared/userPhoto/UserPhoto.tsx
> +    return url.match(/\.(jpeg|jpg|gif|png)$/) != null || url.startsWith('blob:');
That`s a feauture for time when we dont have normal data in backend

2020-11-02 07:29 UTC, oleksandrstarov approved these changes

2020-11-02 08:35 UTC, merged