Added Google OAuth service for frontend which returns user tokenAPI
apastuhov/sigma-js-internship-2020 pull request #71
Opened 2020-10-28 12:16 UTC by romanazaruk

Added Google OAuth service for frontend  which returns user tokenAPI

2020-10-28 22:15 UTC, oleksandrstarov requested changes

2020-10-28 22:15 UTC, oleksandrstarov commented on backend/src/adapter/google-oauth.ts
> +const client = new google.auth.OAuth2('341926743470-9blkj1v16puk169ke04vsk7qigumb8tb.apps.googleusercontent.com');
move key to the const variable (it is used 2 times)

2020-10-28 22:15 UTC, oleksandrstarov commented on frontend/src/components/pages/login/Login.tsx
> +    url: 'http://localhost:8000/api/googleLogin',
http://localhost:8000 is hardcode value - please extract ot the dynamic window object property

2020-10-30 14:18 UTC, OrestHaponov approved these changes
LGTM

2020-10-30 14:58 UTC, oleksandrstarov approved these changes

2020-10-30 15:26 UTC, merged